version: '2'
services:
  bitcoind:
    image: beam/bitcoind:0.18.0
    build: "./bitcoind"
    ports:
      # faucet api
      - "3001:3000"
    expose:
      # rpc api
      - "18443"
    volumes:
      - ./data/bitcoind:/home/bitcoin/.bitcoin

  electrumx:
    image: beam/electrumx:1.12.0
    build: "./electrumx"
    depends_on:
      - "bitcoind"
    ports:
      - "55002:50002"
      - "55001:50001"
    expose:
      - "50001"
      - "50002"
    volumes:
      - ./data/electrumx:/data
    environment:
      # bitcoind is valid
      - DAEMON_URL=http://electrum:electrum@bitcoind:18443
      - COIN=BitcoinSegwit
      - NET=regtest
      # 127.0.0.1 or electrumx is valid for RPC_HOST
      - RPC_HOST=electrumx
      - RPC_PORT=18443
      - HOST=electrumx
      - TCP_PORT=50001
      - SSL_PORT=50002
