version: '2'
services:
  bitcoind:
    image: beam/bitcoind:0.18.0
    build: "./bitcoind"
    container_name:  bitcoind:0.18.0
    ports:
      # faucet api
      - "3001:3000"
    expose:
      # rpc api
      - "18443"
    volumes:
      - ./data/bitcoind:/home/bitcoin/.bitcoin

  electrumx:
    image: beam/electrumx:1.12.0
    build: "./electrumx"
    depends_on:
      - "bitcoind"
    ports:
      - "55002:50002"
      - "55001:50001"
    expose:
      - "50001"
      - "50002"
    volumes:
      - ./data/electrumx:/data
